import React from 'react';

import Head from 'next/head';

type PropsType = {
  description?: string;
  title: string;
};

export const HeadMeta = (props: PropsType) => {
  const { description, title } = props;

  return (
    <Head>
      <title>{title}</title>
      <meta content={description || 'Generated by create next app'} name={'description'} />
      <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
      <link href={'/favicon.ico'} rel={'icon'} />
    </Head>
  );
};
